Master
bedag/helm-charts pull request #136
Opened 2024-10-08 09:24 UTC by ytsurk

**What this PR does**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Notes for Reviewer**:

**Checklist**:

- [ ] Pull Request title in format `[chart]: Changed Something`
- [ ] Updated documentation in the  `README.md.gotmpl` file and executed `helm-docs` 
- [ ] Chart Version bumped
- [ ] All commits are signed-off

2024-10-10 07:25 UTC, lichtloescher requested changes
Could you also bump the chart version?

https://github.com/bedag/helm-charts/blob/master/charts/common/Chart.yaml

2024-10-13 19:00 UTC, ytsurk commented
Done. Did not expect a straight release ;)

2024-10-21 11:42 UTC, wthhub commented
Thank you for your contribution, the functional part is fine!
Could you please extend the schema in [values.schema.json](https://github.com/bedag/helm-charts/blob/2f0169622e6ba8d469799e3640f7a27a182851b8/charts/common/values.schema.json#L766) to reflect the changes and also add an example of the new values in [values.yaml](https://github.com/bedag/helm-charts/blob/2f0169622e6ba8d469799e3640f7a27a182851b8/charts/common/values.yaml#L199)? This will help ensure that everything is documented correctly and improves the user experience.

Thanks in advance!

2025-02-27 16:35 UTC, wthhub commented
opened new pr: https://github.com/bedag/helm-charts/pull/149

2025-02-27 16:35 UTC, closed without merging