[nexus-sonatype-casc]; Initial Release
bedag/helm-charts pull request #48
Opened 2021-05-04 12:12 UTC by oliverbaehler

**What this PR does**:

Adds a new chart to the repository.

**Notes for Reviewer**:

**Checklist**:

- [ ] Pull Request title in format `[chart]: Changed Something`
- [ ] Updated documentation in the  `README.md.gotmpl` file and executed `helm-docs` 
- [ ] Chart Version bumped
- [ ] All commits are signed-off

2021-05-04 12:48 UTC, chifu1234 approved these changes
lgtm

2021-05-11 12:57 UTC, janfuhrer requested changes

2021-05-11 12:57 UTC, janfuhrer commented on charts/sonatype-nexus3-casc/README.md.gotmpl
> +This Chart mainly allows to deploy additional resources to declarative configure sonatype nexus3. The corresponding Docker Iamge can be found here: [https://hub.docker.com/r/bedag/nexus-casc](https:/
typo in `... Docker Iamge ...`

2024-10-04 17:50 UTC, ln-ro commented
Closing PR due to inactivity

2024-10-04 17:50 UTC, closed without merging